name: 'NGINX Instance Manager Publisher for GitOps Workflows'
description: 'Publishes NGINX config files to instances using NGINX Instance manager when there is a repository change event'
author: 'Daniel Edgar'
inputs:
  token:
    required: true
    description: 'The GitHub token for the action to use in order to access the repo'
    default: ${{ github.token }}
  owner:
    required: true
    description: 'The GitHub owner of the repo to monitor. If unspecified, defaults to the owner of the repo wherein this action is running'
    default: ${{ github.repository_owner }}
  repo:
    required: true
    description: 'The GitHub repo to monitor. If unspecified, defaults to the repo wherein this action is running'
    default: ${{ github.event.repository.name }}
  nim_url:
    required: true
    description: 'The URL of the NIM host to publish configs to'
  nim_api_token:
    required: true
    description: 'The API token used to publish to NIM'
  conf_files_directory:
    required: true
    description: 'The name of the subdirectory in your repo that contains NGINX configuration files to be published to NGINX NGINX Instance Manager'
  aux_files_directory:
    required: false
    description: 'The name of the subdirectory in your repo that contains auxillary files to be published to NGINX NGINX Instance Manager'

runs:
  using: 'node16'
  main: 'dist/index.js'
